service: sensitive-artifact-services

# Use the serverless-webpack plugin to transpile ES6
plugins:
  - serverless-webpack
  - serverless-offline

custom:
  # stage: ${opt:stage, self:provider.stage}
  profile:
    dev: default
    prod: ucr-production
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

provider:
  name: aws
  runtime: nodejs8.10
  region: us-west-2
  stage: prod
  # profile: ${self:custom.profile.${self:custom.stage}}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-west-2:*:*"

functions:
  create-note:
    handler: notes/create.main
    events:
      - http:
          path: notes
          method: post
          cors: true
          authorizer: aws_iam
  get-note:
      handler: notes/get.main
      events:
        - http:
          path: notes/{id}
          method: get
          cors: true
          authorizer: aws-iam