service: sensitive-artifact-services

custom:
  stage: ${opt:stage, self:provider.stage}
  profile:
    prod: ucr-production
    dev: default

provider:
  name: aws
  runtime: nodejs8.10
  region: us-west-1
  profile: ${self:custom.profile.${self:custom.stage}}

  environment:
    ARTIFACTS_TABLE: ${self:service}-${opt:stage, self:provider.stage}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.ARTIFACTS_TABLE}"

functions:
  auth:
    handler: auth.handler
    cors: true

  create:
    handler: artifacts/create.create
    events:
      - http:
          path: artifacts
          method: post
          cors: true

  list:
    handler: artifacts/list.list
    events:
      - http:
          path: artifacts
          method: get
          cors: true

  get:
    handler: artifacts/get.get
    events:
      - http:
          path: artifacts/{id}
          method: get
          cors: true

  update:
    handler: artifacts/update.update
    events:
      - http:
          path: artifacts/{id}
          method: put
          cors: true

  delete:
    handler: artifacts/delete.delete
    events:
      - http:
          path: artifacts/{id}
          method: delete
          cors: true

resources:
  Resources:
    AuthFailureGatewayResponse:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: 'ApiGatewayRestApi'
    ServerErrorGatewayResponse:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_5XX
        RestApiId:
          Ref: 'ApiGatewayRestApi'